### Endpoint de teste
GET http://localhost:3003/ping


### 1) Signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Márleo",
    "email": "marleo@gmail.com",
    "password": "123456",
    "role": "ADMIN"
}

### 2) Login
GET http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "marleo@gmail.com",
    "password": "123456"
}

### 2) Deletar usuário
DELETE  http://localhost:3003/users/:id
Authorization: 